// <auto-generated />
using System;
using ConcertTickets;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConcertTickets.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221124113245_ConfigureFields")]
    partial class ConfigureFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConcertTickets.Concert", b =>
                {
                    b.Property<int>("ConcertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupOrArtistName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("TicketsCount")
                        .HasColumnType("int");

                    b.HasKey("ConcertId");

                    b.ToTable("Concerts");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Concert");
                });

            modelBuilder.Entity("ConcertTickets.ClassicalConcert", b =>
                {
                    b.HasBaseType("ConcertTickets.Concert");

                    b.Property<string>("ConcertName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VoiceType")
                        .HasColumnType("int");

                    b.Property<string>("СomposerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ClassicalConcert");
                });

            modelBuilder.Entity("ConcertTickets.OpenAirConcert", b =>
                {
                    b.HasBaseType("ConcertTickets.Concert");

                    b.Property<string>("HeadLiner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HowToGetTo")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("OpenAirConcert");
                });

            modelBuilder.Entity("ConcertTickets.PartyConcert", b =>
                {
                    b.HasBaseType("ConcertTickets.Concert");

                    b.Property<int>("AgeLimitt")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("PartyConcert");
                });
#pragma warning restore 612, 618
        }
    }
}
